/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "hireyuxumqbilinyqhkw"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhpcmV5dXh1bXFiaWxpbnlxaGt3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM0MTE2NjcsImV4cCI6MjA4ODk4NzY2N30.kYdAq5-yoPq3jbXmo0dEI849iZ-k7BYmy9ZyoF7SPGE"